name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        env:
          NIX_INSTALLER_EXTRA_CONF: sandbox = false
      - uses: DeterminateSystems/flakehub-cache-action@v2
      - run: nix flake check -L --show-trace
